import json
import os
from pathlib import Path
from typing import Dict, List, Any, Optional
from dataclasses import dataclass, asdict
import shutil

from utils import get_config_path, ensure_dir


@dataclass
class ProjectType:
    name: str
    extensions: List[str]


class ConfigManager:
    def __init__(self):
        # PyInstaller uyumlu path ayarları
        self.config_dir = ensure_dir(Path.home() / '.codefuser' / 'config')
        self.user_settings_path = self.config_dir / "user_settings.json"
        
        self._default_settings = self._load_default_settings()
        self._user_settings = self._load_user_settings()
        self._merged_settings = self._merge_settings()
    
    def _load_default_settings(self) -> Dict[str, Any]:
        try:
            default_path = get_config_path('default_settings.json')
            with open(default_path, 'r', encoding='utf-8') as f:
                return json.load(f)
        except (FileNotFoundError, Exception) as e:
            print(f"⚠️ Using fallback settings: {e}")
            return self._get_fallback_settings()
    
    def _load_user_settings(self) -> Dict[str, Any]:
        if self.user_settings_path.exists():
            try:
                with open(self.user_settings_path, 'r', encoding='utf-8') as f:
                    return json.load(f)
            except (json.JSONDecodeError, IOError):
                return {}
        return {}
    
    def _merge_settings(self) -> Dict[str, Any]:
        merged = self._default_settings.copy()
        self._deep_merge(merged, self._user_settings)
        return merged
    
    def _deep_merge(self, base: Dict[str, Any], update: Dict[str, Any]) -> None:
        for key, value in update.items():
            if key in base and isinstance(base[key], dict) and isinstance(value, dict):
                self._deep_merge(base[key], value)
            else:
                base[key] = value
    
    def get(self, key: str, default: Any = None) -> Any:
        keys = key.split('.')
        value = self._merged_settings
        
        for k in keys:
            if isinstance(value, dict) and k in value:
                value = value[k]
            else:
                return default
        
        return value
    
    def set(self, key: str, value: Any) -> None:
        keys = key.split('.')
        
        if not self._user_settings:
            self._user_settings = {}
        
        current = self._user_settings
        for k in keys[:-1]:
            if k not in current:
                current[k] = {}
            current = current[k]
        
        current[keys[-1]] = value
        self._save_user_settings()
        self._merged_settings = self._merge_settings()
    
    def _save_user_settings(self) -> None:
        with open(self.user_settings_path, 'w', encoding='utf-8') as f:
            json.dump(self._user_settings, f, ensure_ascii=False, indent=4)
    
    def reset_to_defaults(self) -> None:
        if self.user_settings_path.exists():
            self.user_settings_path.unlink()
        self._user_settings = {}
        self._merged_settings = self._default_settings.copy()
    
    def get_project_types(self) -> Dict[str, List[str]]:
        return self.get('project_types', {})
    
    def add_project_type(self, name: str, extensions: List[str]) -> None:
        project_types = self.get_project_types()
        project_types[name] = extensions
        self.set('project_types', project_types)
    
    def get_ignored_folders(self) -> List[str]:
        return self.get('ignore_folders', [])
    
    def get_ignored_files(self) -> List[str]:
        return self.get('ignore_files', [])
    
    def get_language(self) -> str:
        return self.get('language', 'tr')
    
    def set_language(self, language: str) -> None:
        self.set('language', language)
    
    def get_output_format(self) -> str:
        return self.get('output_settings.default_format', 'txt')
    
    def get_available_formats(self) -> List[str]:
        return self.get('output_settings.available_formats', ['txt'])
    
    def export_settings(self, filepath: Path) -> None:
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(self._merged_settings, f, ensure_ascii=False, indent=4)
    
    def import_settings(self, filepath: Path) -> None:
        with open(filepath, 'r', encoding='utf-8') as f:
            imported_settings = json.load(f)
        
        self._user_settings = imported_settings
        self._save_user_settings()
        self._merged_settings = self._merge_settings()
    
    def _get_fallback_settings(self) -> Dict[str, Any]:
        """Fallback settings when default_settings.json is not found"""
        return {
            "language": "tr",
            "project_types": {
                "Python": [".py", ".pyw"],
                "JavaScript": [".js", ".jsx", ".ts", ".tsx"],
                "Web": [".html", ".css", ".scss", ".sass"],
                "Java": [".java"],
                "C++": [".cpp", ".h", ".hpp", ".c"],
                "C#": [".cs"],
                "Go": [".go"],
                "Rust": [".rs"],
                "Ruby": [".rb"],
                "PHP": [".php"],
                "Swift": [".swift"],
                "Kotlin": [".kt", ".kts"],
                "Dart": [".dart"],
                "R": [".r", ".R"],
                "MATLAB": [".m"],
                "Julia": [".jl"],
                "Scala": [".scala"],
                "SQL": [".sql"],
                "Shell": [".sh", ".bash", ".zsh", ".fish"],
                "PowerShell": [".ps1", ".psm1"],
                "Batch": [".bat", ".cmd"],
                "Lua": [".lua"],
                "Perl": [".pl", ".pm"],
                "Haskell": [".hs"],
                "Clojure": [".clj", ".cljs"],
                "Elixir": [".ex", ".exs"],
                "Erlang": [".erl"],
                "F#": [".fs", ".fsx"],
                "OCaml": [".ml", ".mli"],
                "Nim": [".nim"],
                "Crystal": [".cr"],
                "Zig": [".zig"],
                "V": [".v"],
                "D": [".d"],
                "Pascal": [".pas", ".pp"],
                "Fortran": [".f90", ".f95", ".f03"],
                "COBOL": [".cob", ".cbl"],
                "Ada": [".ada", ".adb", ".ads"],
                "Prolog": [".pl", ".pro"],
                "Lisp": [".lisp", ".lsp"],
                "Scheme": [".scm", ".ss"],
                "Racket": [".rkt"],
                "VB.NET": [".vb"],
                "Objective-C": [".m", ".mm"],
                "Groovy": [".groovy"],
                "CoffeeScript": [".coffee"],
                "Elm": [".elm"],
                "ReasonML": [".re", ".rei"],
                "PureScript": [".purs"],
                "Solidity": [".sol"],
                "Vyper": [".vy"],
                "Move": [".move"],
                "Cairo": [".cairo"],
                "Noir": [".nr"],
                "VHDL": [".vhd", ".vhdl"],
                "Verilog": [".v", ".sv"],
                "SystemVerilog": [".sv"],
                "Assembly": [".asm", ".s"],
                "WebAssembly": [".wat", ".wasm"],
                "CUDA": [".cu", ".cuh"],
                "OpenCL": [".cl"],
                "GLSL": [".glsl", ".vert", ".frag"],
                "HLSL": [".hlsl"],
                "Dockerfile": ["Dockerfile", ".dockerfile"],
                "Makefile": ["Makefile", "makefile", ".mk"],
                "CMake": ["CMakeLists.txt", ".cmake"],
                "Gradle": [".gradle", ".gradle.kts"],
                "Maven": ["pom.xml"],
                "Bazel": ["BUILD", ".bazel", ".bzl"],
                "JSON": [".json", ".jsonc"],
                "XML": [".xml"],
                "YAML": [".yaml", ".yml"],
                "TOML": [".toml"],
                "INI": [".ini", ".cfg", ".conf"],
                "Properties": [".properties"],
                "Markdown": [".md", ".markdown"],
                "reStructuredText": [".rst"],
                "AsciiDoc": [".adoc", ".asciidoc"],
                "LaTeX": [".tex", ".latex"],
                "Org": [".org"],
                "Pod": [".pod"],
                "RDoc": [".rdoc"],
                "Textile": [".textile"],
                "MediaWiki": [".wiki"],
                "Creole": [".creole"],
                "BBCode": [".bbcode"],
                "Jupyter": [".ipynb"],
                "R Markdown": [".rmd"],
                "Quarto": [".qmd"],
                "GraphQL": [".graphql", ".gql"],
                "Protocol Buffers": [".proto"],
                "Thrift": [".thrift"],
                "Cap'n Proto": [".capnp"],
                "MessagePack": [".msgpack"],
                "FlatBuffers": [".fbs"],
                "Avro": [".avsc", ".avdl"],
                "OpenAPI": [".openapi.yaml", ".openapi.json"],
                "AsyncAPI": [".asyncapi.yaml", ".asyncapi.json"],
                "Smithy": [".smithy"],
                "Terraform": [".tf", ".tfvars"],
                "CloudFormation": [".cfn.yaml", ".cfn.json"],
                "Ansible": [".ansible.yaml", ".ansible.yml"],
                "Puppet": [".pp"],
                "Chef": [".rb"],
                "SaltStack": [".sls"],
                "Vagrant": ["Vagrantfile"],
                "Docker Compose": ["docker-compose.yaml", "docker-compose.yml"],
                "Kubernetes": [".k8s.yaml", ".k8s.yml"],
                "Helm": ["Chart.yaml", "values.yaml"],
                "Nix": [".nix"],
                "Dhall": [".dhall"],
                "Jsonnet": [".jsonnet", ".libsonnet"],
                "CUE": [".cue"],
                "HCL": [".hcl"],
                "Pkl": [".pkl"],
                "KCL": [".k"],
                "Starlark": [".star", ".bzl"],
                "Tcl": [".tcl"],
                "AWK": [".awk"],
                "sed": [".sed"],
                "m4": [".m4"],
                "PostScript": [".ps", ".eps"],
                "Forth": [".forth", ".fth"],
                "APL": [".apl"],
                "J": [".ijs"],
                "K": [".k"],
                "Q": [".q"],
                "MATLAB": [".m"],
                "Octave": [".m"],
                "Scilab": [".sci", ".sce"],
                "IDL": [".pro"],
                "NCL": [".ncl"],
                "GDScript": [".gd"],
                "Godot": [".tscn", ".tres"],
                "Unity": [".unity", ".prefab"],
                "Unreal": [".uasset", ".umap"],
                "GameMaker": [".gml"],
                "Construct": [".c3p"],
                "Scratch": [".sb3"],
                "Blockly": [".blockly"],
                "LabVIEW": [".vi", ".ctl"],
                "Simulink": [".slx", ".mdl"],
                "Modelica": [".mo"],
                "AMPL": [".mod", ".dat"],
                "GAMS": [".gms"],
                "Julia": [".jl"],
                "Stan": [".stan"],
                "BUGS": [".bugs"],
                "JAGS": [".jags"],
                "SAS": [".sas"],
                "SPSS": [".sps"],
                "Stata": [".do", ".ado"],
                "EViews": [".prg"],
                "Gretl": [".inp"],
                "Maple": [".mpl", ".mw"],
                "Mathematica": [".nb", ".m"],
                "Maxima": [".mac", ".wxm"],
                "Sage": [".sage", ".sagews"],
                "SymPy": [".py"],
                "Lean": [".lean"],
                "Coq": [".v"],
                "Agda": [".agda"],
                "Idris": [".idr"],
                "Dafny": [".dfy"],
                "Why3": [".why", ".mlw"],
                "F*": [".fst", ".fsti"],
                "TLA+": [".tla"],
                "Alloy": [".als"],
                "Z3": [".smt2"],
                "Promela": [".pml"],
                "NuSMV": [".smv"],
                "UPPAAL": [".xml", ".q"],
                "Petri nets": [".pnml"],
                "BPMN": [".bpmn"],
                "UML": [".uml", ".xmi"],
                "SysML": [".sysml"],
                "Archimate": [".archimate"],
                "C4": [".c4"],
                "PlantUML": [".puml", ".plantuml"],
                "Mermaid": [".mmd", ".mermaid"],
                "Graphviz": [".dot", ".gv"],
                "yEd": [".graphml"],
                "Draw.io": [".drawio", ".dio"],
                "Lucidchart": [".lucid"],
                "Visio": [".vsdx"],
                "Gliffy": [".gliffy"],
                "Cacoo": [".cacoo"],
                "Creately": [".creately"],
                "Figma": [".fig"],
                "Sketch": [".sketch"],
                "Adobe XD": [".xd"],
                "Framer": [".framer"],
                "InVision": [".invision"],
                "Zeplin": [".zeplin"],
                "Abstract": [".abstract"],
                "Avocode": [".avocode"],
                "Marvel": [".marvel"],
                "Proto.io": [".protoio"],
                "Axure": [".rp"],
                "Balsamiq": [".bmpr"],
                "Mockplus": [".mp"],
                "Justinmind": [".jm"],
                "UXPin": [".uxpin"],
                "Origami": [".origami"],
                "Principle": [".principle"],
                "Flinto": [".flinto"],
                "ProtoPie": [".protopie"],
                "Kite": [".kite"],
                "Haiku": [".haiku"],
                "Lottie": [".json"],
                "Rive": [".riv"],
                "Spine": [".spine"],
                "DragonBones": [".dbproj"],
                "Spriter": [".scml"],
                "Creature": [".creature"],
                "COA Tools": [".coa"],
                "CSS": [".css", ".scss", ".sass", ".less", ".styl"],
                "Tailwind": [".css"],
                "Bootstrap": [".css"],
                "Bulma": [".css"],
                "Foundation": [".css"],
                "Materialize": [".css"],
                "Semantic UI": [".css"],
                "Ant Design": [".css"],
                "Material-UI": [".css"],
                "Chakra UI": [".css"],
                "Element": [".css"],
                "Vuetify": [".css"],
                "Quasar": [".css"],
                "PrimeVue": [".css"],
                "Naive UI": [".css"],
                "Arco Design": [".css"],
                "Vant": [".css"],
                "NutUI": [".css"],
                "Taro UI": [".css"],
                "uView": [".css"],
                "Vux": [".css"],
                "Mint UI": [".css"],
                "Cube UI": [".css"],
                "Muse UI": [".css"],
                "AT-UI": [".css"],
                "iView": [".css"],
                "Spectre": [".css"],
                "Milligram": [".css"],
                "Skeleton": [".css"],
                "Pure": [".css"],
                "UIkit": [".css"],
                "Metro UI": [".css"],
                "Onsen UI": [".css"],
                "Framework7": [".css"],
                "Ionic": [".css"],
                "jQuery Mobile": [".css"],
                "Kendo UI": [".css"],
                "Webix": [".css"],
                "DHTMLX": [".css"],
                "ExtJS": [".css"],
                "YUI": [".css"],
                "Dojo": [".css"],
                "MooTools": [".css"],
                "Prototype": [".css"],
                "script.aculo.us": [".css"],
                "Zepto": [".css"],
                "Cash": [".css"],
                "Umbrella": [".css"],
                "Alpine": [".css"],
                "htmx": [".css"],
                "Turbo": [".css"],
                "Stimulus": [".css"],
                "Hotwire": [".css"],
                "LiveView": [".css"],
                "LiveWire": [".css"],
                "Inertia": [".css"],
                "Remix": [".css"],
                "Fresh": [".css"],
                "Aleph": [".css"],
                "Ultra": [".css"],
                "Astro": [".astro"],
                "SvelteKit": [".svelte"],
                "Nuxt": [".vue"],
                "Next": [".jsx", ".tsx"],
                "Gatsby": [".jsx", ".tsx"],
                "Gridsome": [".vue"],
                "VuePress": [".vue"],
                "VitePress": [".vue"],
                "Docusaurus": [".jsx", ".tsx"],
                "Nextra": [".jsx", ".tsx"],
                "Docsify": [".md"],
                "GitBook": [".md"],
                "MkDocs": [".md"],
                "Sphinx": [".rst"],
                "Jekyll": [".md"],
                "Hugo": [".md"],
                "Eleventy": [".md"],
                "Hexo": [".md"],
                "Pelican": [".md"],
                "Metalsmith": [".md"],
                "Wintersmith": [".md"],
                "Middleman": [".md"],
                "Nanoc": [".md"],
                "Sculpin": [".md"],
                "Statamic": [".md"],
                "Kirby": [".md"],
                "Grav": [".md"],
                "October": [".md"],
                "Craft": [".md"],
                "WordPress": [".php"],
                "Drupal": [".php"],
                "Joomla": [".php"],
                "Magento": [".php"],
                "PrestaShop": [".php"],
                "OpenCart": [".php"],
                "WooCommerce": [".php"],
                "Shopify": [".liquid"],
                "BigCommerce": [".html"],
                "Squarespace": [".html"],
                "Wix": [".html"],
                "Webflow": [".html"],
                "Bubble": [".json"],
                "Adalo": [".json"],
                "Glide": [".json"],
                "Softr": [".json"],
                "Stacker": [".json"],
                "Airtable": [".json"],
                "Notion": [".json"],
                "Coda": [".json"],
                "Roam": [".json"],
                "Obsidian": [".md"],
                "Logseq": [".md"],
                "RemNote": [".md"],
                "Dendron": [".md"],
                "Foam": [".md"],
                "TiddlyWiki": [".tid"],
                "Zettlr": [".md"],
                "Typora": [".md"],
                "Mark Text": [".md"],
                "Notable": [".md"],
                "Joplin": [".md"],
                "Standard Notes": [".md"],
                "Simplenote": [".md"],
                "Bear": [".md"],
                "Ulysses": [".md"],
                "iA Writer": [".md"],
                "Byword": [".md"],
                "WriteRoom": [".md"],
                "FoldingText": [".md"],
                "TaskPaper": [".taskpaper"],
                "Things": [".things"],
                "OmniFocus": [".omnifocus"],
                "Todoist": [".todoist"],
                "Any.do": [".anydo"],
                "TickTick": [".ticktick"],
                "Microsoft To Do": [".todo"],
                "Google Tasks": [".tasks"],
                "Remember The Milk": [".rtm"],
                "Habitica": [".habitica"],
                "Trello": [".trello"],
                "Asana": [".asana"],
                "Monday": [".monday"],
                "ClickUp": [".clickup"],
                "Basecamp": [".basecamp"],
                "Jira": [".jira"],
                "Linear": [".linear"],
                "Shortcut": [".shortcut"],
                "Pivotal Tracker": [".pivotal"],
                "GitHub Projects": [".github"],
                "GitLab": [".gitlab"],
                "Bitbucket": [".bitbucket"],
                "Azure DevOps": [".azure"],
                "AWS CodeCommit": [".aws"],
                "Google Cloud Source": [".google"],
                "Gitea": [".gitea"],
                "Gogs": [".gogs"],
                "Phabricator": [".phabricator"],
                "Review Board": [".reviewboard"],
                "Gerrit": [".gerrit"],
                "Crucible": [".crucible"],
                "Upsource": [".upsource"],
                "CodeStream": [".codestream"],
                "CodeScene": [".codescene"],
                "SonarQube": [".sonar"],
                "Codacy": [".codacy"],
                "Code Climate": [".codeclimate"],
                "Coverity": [".coverity"],
                "Veracode": [".veracode"],
                "Checkmarx": [".checkmarx"],
                "Fortify": [".fortify"],
                "Snyk": [".snyk"],
                "WhiteSource": [".whitesource"],
                "Black Duck": [".blackduck"],
                "FOSSA": [".fossa"],
                "License Finder": [".licensefinder"],
                "CycloneDX": [".cyclonedx"],
                "SPDX": [".spdx"],
                "Renovate": [".renovate"],
                "Dependabot": [".dependabot"],
                "Greenkeeper": [".greenkeeper"],
                "David": [".david"],
                "npm-check": [".npmcheck"],
                "Yarn": [".yarn"],
                "pnpm": [".pnpm"],
                "Bower": [".bower"],
                "Composer": [".composer"],
                "Bundler": [".bundler"],
                "Cargo": [".cargo"],
                "Go Modules": [".gomod"],
                "Maven": [".maven"],
                "Gradle": [".gradle"],
                "Ant": [".ant"],
                "Make": [".make"],
                "CMake": [".cmake"],
                "Bazel": [".bazel"],
                "Buck": [".buck"],
                "Pants": [".pants"],
                "Please": [".please"],
                "Ninja": [".ninja"],
                "Meson": [".meson"],
                "SCons": [".scons"],
                "Waf": [".waf"],
                "Rake": [".rake"],
                "Jake": [".jake"],
                "Grunt": [".grunt"],
                "Gulp": [".gulp"],
                "Webpack": [".webpack"],
                "Rollup": [".rollup"],
                "Parcel": [".parcel"],
                "Vite": [".vite"],
                "esbuild": [".esbuild"],
                "swc": [".swc"],
                "Rome": [".rome"],
                "Turbopack": [".turbopack"],
                "Bun": [".bun"],
                "Deno": [".deno"],
                "Node": [".node"],
                "Python": [".python"],
                "Ruby": [".ruby"],
                "PHP": [".php"],
                "Java": [".java"],
                "C#": [".csharp"],
                "Go": [".go"],
                "Rust": [".rust"],
                "Swift": [".swift"],
                "Kotlin": [".kotlin"],
                "Dart": [".dart"],
                "Scala": [".scala"],
                "Clojure": [".clojure"],
                "Elixir": [".elixir"],
                "Erlang": [".erlang"],
                "Haskell": [".haskell"],
                "OCaml": [".ocaml"],
                "F#": [".fsharp"],
                "Reason": [".reason"],
                "Elm": [".elm"],
                "PureScript": [".purescript"],
                "Nim": [".nim"],
                "Crystal": [".crystal"],
                "Zig": [".zig"],
                "V": [".vlang"],
                "D": [".dlang"],
                "Julia": [".julia"],
                "R": [".rlang"],
                "MATLAB": [".matlab"],
                "Octave": [".octave"],
                "Scilab": [".scilab"],
                "IDL": [".idl"],
                "NCL": [".ncl"],
                "Fortran": [".fortran"],
                "COBOL": [".cobol"],
                "Ada": [".ada"],
                "Pascal": [".pascal"],
                "Delphi": [".delphi"],
                "Lazarus": [".lazarus"],
                "FreePascal": [".freepascal"],
                "Modula": [".modula"],
                "Oberon": [".oberon"],
                "Simula": [".simula"],
                "Smalltalk": [".smalltalk"],
                "Objective-C": [".objc"],
                "Groovy": [".groovy"],
                "Lua": [".lua"],
                "Tcl": [".tcl"],
                "Perl": [".perl"],
                "Raku": [".raku"],
                "AWK": [".awk"],
                "sed": [".sed"],
                "Bash": [".bash"],
                "Zsh": [".zsh"],
                "Fish": [".fish"],
                "PowerShell": [".powershell"],
                "Batch": [".batch"],
                "VBScript": [".vbscript"],
                "AppleScript": [".applescript"],
                "AutoHotkey": [".autohotkey"],
                "AutoIt": [".autoit"]
            },
            "ignore_folders": [
                "__pycache__", ".git", ".svn", ".hg", ".bzr", ".DS_Store",
                "node_modules", "venv", "env", ".env", "virtualenv",
                ".venv", "build", "dist", "out", "bin", "obj",
                ".idea", ".vscode", ".vs", "*.egg-info", ".pytest_cache",
                ".mypy_cache", ".tox", ".coverage", "htmlcov",
                ".gradle", ".maven", "target", ".sass-cache",
                ".next", ".nuxt", ".cache", "coverage", ".nyc_output",
                ".hypothesis", ".jupyter", ".ipynb_checkpoints",
                "Thumbs.db", "desktop.ini", ".DS_Store", ".localized",
                ".Spotlight-V100", ".Trashes", ".fseventsd", ".VolumeIcon.icns",
                ".com.apple.timemachine*", ".TemporaryItems", ".apdisk",
                ".ropeproject", "__pypackages__", "*.pyc", ".Python",
                "pip-log.txt", "pip-delete-this-directory.txt",
                ".webassets-cache", ".scrapy", "*.log", "*.pot",
                "local_settings.py", "db.sqlite3", "instance",
                ".spyderproject", ".spyproject", "celerybeat-schedule",
                "*.sage.py", ".dmypy.json", "dmypy.json", ".pyre",
                "vendor", "bower_components", "jspm_packages",
                "web_modules", "*.tsbuildinfo", ".npm", ".eslintcache",
                ".rpt2_cache", ".rts2_cache_cjs", ".rts2_cache_es",
                ".rts2_cache_umd", ".parcel-cache", ".docusaurus",
                ".serverless", ".fusebox", ".dynamodb", ".tern-port",
                ".vscode-test", ".yarn-integrity", "*.pid", "*.seed",
                "*.pid.lock", "lib-cov", "*.lcov", ".grunt",
                ".lock-wscript", "typings", ".node_repl_history",
                "*.tgz", ".yarn-metadata.json", ".yarn-install-state.gz",
                ".pnp.cjs", ".pnp.loader.mjs", "__pypackages__",
                "CMakeCache.txt", "CMakeFiles", "CMakeScripts",
                "Testing", "Makefile", "cmake_install.cmake",
                "install_manifest.txt", "compile_commands.json",
                "CTestTestfile.cmake", "_deps", ".ccls-cache",
                ".vim", ".netrwhist", "*~", ".projectile",
                ".dir-locals.el", "flycheck_*.el", ".envrc",
                "tramp", ".lsp-session-v1", ".dap-breakpoints",
                ".ert-runs", "eshell/history", "eshell/lastdir",
                "elpa", "auto-save-list", ".emacs.desktop",
                ".emacs.desktop.lock", "network-security.data",
                ".nrepl-port", ".cpcache", ".lein-*", ".nrepl-history",
                ".rebel_readline_history", "pom.xml.asc", "*.jar",
                "*.class", ".lein-deps-sum", ".lein-repl-history",
                ".lein-plugins", ".lein-failures", ".calva", ".clj-kondo",
                ".shadow-cljs", ".clerk", ".cljstyle-cache", ".babashka",
                ".nbb", "_build", "deps", ".fetch", "erl_crash.dump",
                "*.ez", "*.beam", ".elixir_ls", ".formatter.exs",
                ".tool-versions", ".rebar3", "_checkouts", ".eunit",
                ".rebar", "logs", "_build", ".erlang.mk", "ebin",
                "rebar.lock", ".concrete/DEV_MODE", ".hg", ".hgignore",
                ".hgsigs", ".hgsub", ".hgsubstate", ".hgtags",
                ".bzr", ".bzrignore", ".fossil-settings", "_FOSSIL_",
                ".fslckout", "_darcs", ".monotone", "_MTN", ".mtn-ignore",
                ".arch-params", "{arch}", ".arch-ids", ",*", "_sgbak",
                "autom4te.cache", ".cvsignore", "CVS", "_$*", "$*",
                "*.tmp", ".builds", ".vercel", ".sst", ".redwood",
                ".docz", ".now", ".netlify", ".serverless_nextjs",
                ".expo", ".expo-shared", ".turbo", ".gitignore",
                ".gitattributes", ".gitmodules", ".mailmap",
                ".dockerignore", "Dockerfile*", "docker-compose*",
                "LICENSE*", "license*", "License*", "NOTICE*",
                "AUTHORS*", "CONTRIBUTORS*", "PATENTS*", "COPYING*",
                "COPYRIGHT*", ".editorconfig", ".eslintrc*",
                ".prettierrc*", ".stylelintrc*", ".markdownlint*",
                ".htmlhintrc*", ".babelrc*", "babel.config*",
                "tsconfig*", "jsconfig*", ".flowconfig",
                "webpack.config*", "rollup.config*", "gulpfile*",
                "Gruntfile*", ".karma*", ".mocha*", "jest.config*",
                ".circleci", ".github", ".gitlab-ci*", ".travis*",
                "appveyor*", ".azure-pipelines*", "bitbucket-pipelines*",
                "buddy*", ".codeship*", ".drone*", "Jenkinsfile*",
                ".semaphore*", ".buildkite*", "cloudbuild*",
                ".woodpecker*", ".zuul*", "shippable*", "wercker*",
                ".teamcity*", "bamboo*", ".gocd*", "concourse*",
                ".codefresh*", ".rancher-pipeline*", ".spinnaker*",
                ".skaffold*", ".fluxcd*", ".argocd*", ".tekton*",
                ".keptn*", ".octopus*", ".harness*", "pulumi*",
                ".terraform*", "terraform.tfstate*", ".terragrunt*",
                ".ansible*", "ansible.cfg", ".vagrant*", "Vagrantfile",
                ".chef*", ".kitchen*", "Berksfile*", "Policyfile*",
                ".inspec*", ".puppet*", "Puppetfile*", ".salt*",
                "pillar*", ".cfn*", "template.yaml", "samconfig*",
                ".ebextensions*", ".elasticbeanstalk*", ".amplify*",
                "amplify*", ".firebase*", "firebase.json", ".gcloudignore",
                "app.yaml", ".app.yaml", "dispatch.yaml", "queue.yaml",
                "index.yaml", "cron.yaml", ".clasp.json", "appsscript.json",
                ".deta*", ".railway*", ".render*", "fly.toml",
                "Procfile*", ".buildpacks", ".slugignore", ".s2iignore",
                ".openshift*", ".okd*", ".minishift*", ".odo*",
                ".devfile*", ".che*", ".crc*", "operator-sdk*",
                ".kubebuilder*", ".kustomize*", "kustomization*",
                ".helmignore", "requirements.lock", ".helmfile*",
                ".flux*", ".argocd-source*", ".werf*", ".gitlab-webide*",
                ".gitpod*", ".devcontainer*", ".codespaces*", ".vscode*",
                ".idea*", ".ijwb*", ".sublime*", ".nova*", ".kate*",
                ".komodo*", ".brackets*", ".c9*", ".codenvy*",
                ".che*", ".theia*", ".orion*", ".dirigible*",
                ".codesandbox*", ".stackblitz*", ".glitch*",
                ".replit*", ".replit", "replit.nix", ".config",
                ".upm", ".pythonlibs", ".breakpoints", ".gitpod.yml",
                "gitpod.Dockerfile", ".github", ".circleci",
                ".travis.yml", ".gitlab-ci.yml", "azure-pipelines.yml",
                ".drone.yml", "Jenkinsfile", ".teamcity", ".buildkite",
                ".woodpecker.yml", ".zuul.yaml", "shippable.yml",
                "wercker.yml", ".semaphore", "buddy.yml", ".codeship",
                "bitbucket-pipelines.yml", "concourse.yml", "codefresh.yml",
                ".rancher-pipeline.yml", ".spinnaker", ".skaffold.yaml",
                ".flux.yaml", ".argo", ".tekton", ".keptn", ".octopus",
                ".harness", ".waypoint.hcl", ".devspace.yaml",
                "space.yaml", ".lagoon.yml", ".platform.app.yaml",
                ".cleverapps", ".scalingo", ".dokku", ".caprover",
                ".kamal", ".coolify", ".porter", ".nanobox",
                ".now.json", "vercel.json", ".vercel", "netlify.toml",
                ".netlify", "_redirects", "_headers", ".well-known",
                ".cargo", ".rustup", ".multirust", ".julia",
                ".juliahistory", ".node-version", ".nvmrc", ".rvmrc",
                ".ruby-version", ".ruby-gemset", ".rbenv-version",
                ".python-version", ".pyenv", ".mypy_cache", "__pycache__",
                ".ruff_cache", ".hypothesis", ".stestr", ".testrepository",
                ".txpkg", "test-results", "test-output", ".tasty-rerun-log",
                ".stack-work", ".HTF", ".ghc.environment*", ".cabal-sandbox",
                "cabal.sandbox.config", ".hsenv", ".sandbox", ".shake",
                ".auto-generated", ".byte-code-cache", ".generated",
                ".pants.d", ".pex", ".pytype", ".dmypy_cache", ".ruff_cache"
            ],
            "ignore_files": [
                "*.pyc", "*.pyo", "*.pyd", ".DS_Store", "Thumbs.db",
                "desktop.ini", "*.swp", "*.swo", "*.swn", "*.bak",
                "*.tmp", "*.temp", "*.log", "*.cache", "*~",
                ".fuse_hidden*", ".directory", ".Trash-*",
                ".nfs*", "*.orig", "*.rej", "*.BACKUP.*",
                "*.BASE.*", "*.LOCAL.*", "*.REMOTE.*"
            ],
            "output_settings": {
                "default_format": "txt",
                "available_formats": ["txt", "html", "docx", "pdf"],
                "max_file_size_mb": 50,
                "encoding": "utf-8"
            },
            "interface": {
                "theme": "dark",
                "font_size": 11,
                "show_line_numbers": true,
                "word_wrap": true,
                "fullscreen": true,
                "window_size": "900x700"
            },
            "performance": {
                "max_workers": 4,
                "chunk_size": 1000,
                "enable_caching": true
            },
            "git": {
                "enabled": true,
                "exclude_gitignored": true
            },
            "smart_filters": {
                "exclude_tests": false,
                "exclude_docs": false,
                "exclude_configs": false,
                "min_file_size": 0,
                "max_file_size": 10485760
            }
        }